name: CI/CD
on:
  pull_request:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x, 12.x, 14.x, 15.x]

    steps:
      - name: Checkout the application
        # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@v2
      - name: Get yarn cache dir
        id: yarn-dir-cache
        run: echo "::set-output name-dir::$(yarn cache dir)"
      - name: Use nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{ runner.os }}-modules-
            ${{ runner.os }}-
      - name: Install dependencies
        uses: yarn install --frozen-lockfile
      - name: Check lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - name: Build the project
        run: yarn build
